MeApp\ProductBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        content:
            type: text
        createAt:
            type: datetime
            column: create_at
        updateAt:
            type: datetime
            column: update_at

    manyToOne:
        user:
            targetEntity: MeApp\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id

    lifecycleCallbacks:
        prePersist:
            - setAtOnPrePersist
        preUpdate:
            - setAtOnPreUpdate
