me_app_demo:
    resource: "@MeAppDemoBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata routing
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin