me_app_platform:
    resource: "@MeAppPlatformBundle/Resources/config/routing.yml"
    prefix:   /

me_app_product:
    resource: "@MeAppProductBundle/Resources/config/routing.yml"
    prefix:   /

me_app_user:
    resource: "@MeAppUserBundle/Resources/config/routing.yml"
    prefix:   /

me_app_demo:
    resource: "@MeAppDemoBundle/Resources/config/routing.yml"
    prefix:   /