parameters:
#    me_app_platform.example.class: MeApp\PlatformBundle\Example

services:
#    me_app_platform.example:
#        class: %me_app_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
