
product_index:
    pattern: /apps
    defaults:
        _controller: MeAppProductBundle:Product:index

product_new:
    pattern: /app/new
    defaults:
        _controller: MeAppProductBundle:ProductForm:new

product_show:
    pattern: /app/{productId}
    defaults:
        _controller: MeAppProductBundle:Product:show

product_edit:
    pattern: /app/{productId}/edit
    defaults:
        _controller: MeAppProductBundle:ProductForm:edit