
product_index:
    pattern: /apps
    defaults:
        _controller: MeAppProductBundle:Product:index

product_show:
    pattern: /app/{productId}
    defaults:
        _controller: MeAppProductBundle:Product:show
