parameters:
#    me_app_product.example.class: MeApp\ProductBundle\Example

services:
    app.db.product:
        class: MeApp\CoreBundle\EntityManager\BaseManager
        arguments: 
            - @doctrine.orm.entity_manager
            - "MeAppProductBundle:Product"
