parameters:
#    me_app_store.example.class: MeApp\StoreBundle\Example

services:
#    me_app_store.example:
#        class: %me_app_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
