parameters:
#    me_app_user.example.class: MeApp\UserBundle\Example

services:
#    me_app_user.example:
#        class: %me_app_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
