parameters:
#    me_app_core.example.class: MeApp\CoreBundle\Example

services:
#    me_app_core.example:
#        class: %me_app_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
